import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    template: '%s | Template', // Applies to child routes, and not the segment it is defined
    default: 'Next.js Default', // Useful when you want a fallback title for child pages
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'lightblue', padding: '10px' }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: 'pink', padding: '10px' }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
